# Generated by Django 4.2.3 on 2023-08-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='imgs',
            field=models.ImageField(blank=True, upload_to='places', verbose_name='Картинка'),
        ),
    ]
