# Generated by Django 4.2.3 on 2023-08-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_imgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('imgs', models.ImageField(upload_to='images/', verbose_name='Картинка')),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='imgs',
        ),
    ]
